language: php

sudo: required

php:
  - 5.6
  - hhvm

before_script:
  - composer install --prefer-source --no-interaction
  - composer self-update
  - mysql -e 'create database database_test;'

script: phpunit

matrix:
  allow_failures:
    - php: 5.6
    - php: hhvm
  fast_finish: true

notifications:
    on_success: never
    on_failure: always

services:
  - redis-server

test:
  adapter: mysql2
  database: database_test
  username: travis
  encoding: utf8